trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GitVersion.SemVer: ''

# resources:
#   containers:
#   - container: pycontainer
#     image: python:3.8

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.402
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
      updateAssemblyInfo: true
# - script: hostname
#   displayName: 'Run a one-line script'

# # Using the task syntax
# - task: CmdLine@2
#   inputs:
#     script: |
#       echo Add other tasks to build, test, and deploy your project.
#       echo See https://aka.ms/yaml
#   env:
#     AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
#   displayName: 'Run a multi-line script'

# - task: CmdLine@2
#   inputs: 
#     script: hostname
#   displayName: 'Asking hostname inside container'
#   target: pycontainer