trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
  - container: pycontainer
    image: python:3.8

steps:
- script: hostname
  displayName: 'Run a one-line script'

# Using the task syntax
- task: CmdLine@2
  inputs:
    script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
  displayName: 'Run a multi-line script'

- task: CmdLine@2
  inputs: 
    script: hostname
  target: pycontainer