trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
  - container: pycontainer
    image: python:3.8

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AnotherTask@1
  target: pycontainer